on:
  push:
    branches:
    - main
jobs:
  compile_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          working-directory: ./resume
          root_file: resume.tex

    
