on:
  push:
    branches:
    - main
    paths:
    - '**.tex'
  workflow_dispatch:
jobs:
  compile_resume:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./resume
          root_file: resume.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: resume.pdf
          path: ./resume/resume.pdf
      - name: Download PDF file in website directory
        uses: actions/download-artifact@v3
        with:
          name: resume.pdf
          path: ./public
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.15.4
        with:
          file_pattern: '*.pdf'
          commit_message: "Resume updated on ${{ env.NOW }}"

