on:
  push:
    branches:
    - main
jobs:
  compile_resume:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./resume
          root_file: resume.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: resume.pdf
          path: resume.pdf
